### ISSUE TITLE
colors don't work?

### ISSUE THREAD

**Issue by isabelroses** [isabelroses/izrss#22]
Minimal reproduction:

Create file called `conf.toml` with the contents as follows
```toml
[colors]
accent = "#B2C98F"
borders = "#46545B"
inverttext = "#252B2E"
subtext = "#6E8585"
text = "#D6CBB4"
```

Run `izrss --config ./conf.toml`

You notice the colors are always wrong.
